### ISSUE TITLE
Fix default permissions to be able to read secrets cluster wide

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/rufio#62]
The default RBAC deployed with Rufio doesn't let it read secrets across namespaces. This is problematic as secrets containing BMC credentials are referenced by Machine resources and could reside in a different namespace.

Kubernetes doesn't currently offer a way to model access to secrets referenced from existing objects so its common practice to allow cluster wide reads and let consumers reconfigure the RBAC to their needs on deployment.

**Comment by pokearu** [comment]
Is the idea to have cluster wide Secret read as the default RBAC or can we instead have the default manifest that Rufio generates to have everything namespaced?
This allows the users to modify the manifest to how they want their cluster permissions to looks like.

**Comment by chrisdoherty4** [comment]
I'm proposing cluster wide read access by default to enable a functional out of the box Rufio.

Trying to restrict to a subset of namespaces requires knowing what those namespaces are which isn't possible as the operator defines them. This approach is adopted by several open source projects already because Kubernetes doesn't offer a way to model transitive access. 

I've been told transitive access is in the works upstream in Kubernetes and will allow operators to define `if I can read A then I can read all Bs referenced by A` which is really what we want.

**Comment by pokearu** [comment]
I am fine with having cluster wide read on `Secrets` by default 👍 I see we do that on [CAPT](https://github.com/tinkerbell/cluster-api-provider-tinkerbell/blob/main/controllers/tinkerbellmachine_controller.go#L50) at the moment as well.
I believe that's how we had it originally but we wanted to make it namespaced, as discussed [here](https://github.com/tinkerbell/rufio/pull/3#discussion_r866327284).
Will update my PR to give cluster wide reads for now.

**Comment by chrisdoherty4** [comment]
Fixed in https://github.com/tinkerbell/rufio/pull/63
