### ISSUE TITLE
ARM Image fails to run on ARM

### ISSUE THREAD

**Issue by christianhuening** [tinkerbell/rufio#74]
## Expected Behaviour

rufio runs on ARM64 systems like the raspberry pi

## Current Behaviour

The image being build is apparently not `arm64` compatible (exec format error)

## Possible Solution

Build multiarch so also arm is supported?

## Context

I am trying to run tinkerbell on raspberry pi's

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu LTS 20

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

K3s on RPi's

**Comment by chrisdoherty4** [comment]
Thanks @christianhuening. Will look into it.

**Comment by chrisdoherty4** [comment]
@christianhuening, did you use the images from `quay.io` or build them yourself?

**Comment by christianhuening** [comment]
From quay.ok

**Comment by chrisdoherty4** [comment]
Thanks

**Comment by jacobweinstock** [comment]
Hey @christianhuening, the latest image, just pushed, is working for me on arm64. Give it a try!

**Comment by christianhuening** [comment]
thanks @jacobweinstock @chrisdoherty4 ! This works like a charm!
